/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */


export const storeProducts = [
  {

    Product_id: 1,
    Title: "Great T-Shirt",
    IMG: "img/img1.jpeg",
    Price: 10,
    Competitor:100,
    Discount:0.7821,
    Size: "L",
    Description:"dummy",
    expireAt: new Date('May 7, 2019 18:36:00'),

    "Seller_id": "someseller",
    "Color": "blue",
    "Brand": "nike",
    "Gender": "men",
    "Category": "clothes",
    "operation": "ADD",
    "cart_id": "llgkjjk",
    "UPC": "1000000",
    "Seller_id": "someseller",

  },
  {
    Product_id: 2,
    Title: "123456789abcdefgh",
    IMG: "img/img2.jpeg",
    Price: 16,
    Competitor:100,
    Discount:0.7821,
    Size: "L",
    Description:"dummy",
   
    expireAt: new Date('May 7, 2019 18:28:00'),
    "Seller_id": "someseller",
    "Color": "blue",
    "Brand": "nike",
    "Gender": "men",
    "Category": "clothes",
    "operation": "ADD",
    "cart_id": "llgkjjk",
    "UPC": "1000000",
    "Seller_id": "someseller",
  },
  {
    Product_id: 3,
    Title: "Nicky Snap Force XII GreenLight Zoom",
    IMG: "img/img3.jpeg",
    Price: 16,
    Competitor:100,
    Discount:0.7821,
    Size: "L",
    Description:"This is a very good shoes that is green and very comfortable which you should pay some money for because it is a really good shoes",   
    expireAt: new Date('May 28, 2019 18:28:00'),

    "Seller_id": "someseller",
    "Color": "blue",
    "Brand": "nike",
    "Gender": "men",
    "Category": "clothes",
    "operation": "ADD",
    "cart_id": "llgkjjk",
    "UPC": "1000000",
    "Seller_id": "someseller",
  },
  {
    Product_id: 4,
    Title: "Item 4",
    IMG: "img/img4.jpeg",
    Price: 16,
    Competitor:100,
    Discount:0.7821,
    Size: "L",
    Description:"dummy",
    expireAt: new Date('May 28, 2019 18:30:00'),

    "Seller_id": "someseller",
    "Color": "blue",
    "Brand": "nike",
    "Gender": "men",
    "Category": "clothes",
    "operation": "ADD",
    "cart_id": "llgkjjk",
    "UPC": "1000000",
    "Seller_id": "someseller",
  },
  {
    Product_id: 5,
    Title: "Item 5",
    IMG: "img/img5.jpeg",
    Price: 16,
    Competitor:100,
    Discount:0.7821,
    Size: "L",
    Description:"dummy",
    expireAt: new Date('May 28, 2019 18:45:00'),


    "Seller_id": "someseller",
    "Color": "blue",
    "Brand": "nike",
    "Gender": "men",
    "Category": "clothes",
    "operation": "ADD",
    "cart_id": "llgkjjk",
    "UPC": "1000000",
    "Seller_id": "someseller",
  },
  {
    Product_id: 6,
    Title: "Item 6",
    IMG: "img/img6.jpeg",
    Price: 16,
    Competitor:100,
    Discount:0.7821,
    Size: "L",
    Description:"dummy",    
    expireAt: new Date('May 28, 2019 18:20:00'),

    "Seller_id": "someseller",
    "Color": "blue",
    "Brand": "nike",
    "Gender": "men",
    "Category": "clothes",
    "operation": "ADD",
    "cart_id": "llgkjjk",
    "UPC": "1000000",
    "Seller_id": "someseller",
  },
  {
    Product_id: 7,
    Title: "item 7",
    IMG: "img/img7.jpeg",
    Price: 30,
    Competitor: 73,
    Discount:0.781,
    Size: "L",
    Description:"dummy",
    expireAt: new Date('May 28, 2019 18:30:00'),

    "Seller_id": "someseller",
    "Color": "blue",
    "Brand": "nike",
    "Gender": "men",
    "Category": "clothes",
    "operation": "ADD",
    "cart_id": "llgkjjk",
    "UPC": "1000000",
    "Seller_id": "someseller",
  },
  {
    Product_id: 8,
    Title: "item 8",
    IMG: "img/img8.jpeg",
    Price: 2,
    Competitor: 73,
    Discount:0.781,
    Size: "L",
    Description:"dummy",    
    expireAt: new Date('May 28, 2019 21:00:00'),

    "Seller_id": "someseller",
    "Color": "blue",
    "Brand": "nike",
    "Gender": "men",
    "Category": "clothes",
    "operation": "ADD",
    "cart_id": "llgkjjk",
    "UPC": "1000000",
    "Seller_id": "someseller",
  },
  {
    Product_id: 9,
    Title: "item 9",
    IMG: "img/img9.jpeg",
    Price: 2,
    Competitor: 73,
    Discount:0.781,
    Size: "L",
    Description: "dummy", 
    expireAt: new Date('May 28, 2019 21:00:00'),

    "Seller_id": "someseller",
    "Color": "blue",
    "Brand": "nike",
    "Gender": "men",
    "Category": "clothes",
    "operation": "ADD",
    "cart_id": "llgkjjk",
    "UPC": "1000000",
    "Seller_id": "someseller",
  },

];

